name: Generate Engine CSV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-csv:
    name: Generate engines csv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies (if needed)
        run: |
          pip install -r tools/requirements.txt || true
      - name: Check if CSV was created
        run: |
          if [ ! -f data/engines.csv ]; then
            echo "engines.csv not found!"
            exit 1
          else
            echo "engines.csv created successfully"
          fi
      - name: 🛠️ Run generate_engine_csv.py
        run: |
          python tools/generate_engine_csv.py

      - name: Upload generated CSV
        uses: actions/upload-artifact@v4
        with:
          name: engines-csv
          path: data/engines.csv

      - name: Upload CSV log file
        uses: actions/upload-artifact@v4
        with:
          name: csv-log
          path: tools/logs/generate_engine_csv.log
