name: Generate Engine CSV

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-csv:
    name: Generate engines csv
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          pip install -r tools/requirements.txt || true

      - name: Run generate_engine_csv.py
        run: |
          python tools/generate_engine_csv.py

      - name: Check if engines.csv was created
        run: |
          if [ ! -f docs/data/engines.csv ]; then
            echo "engines.csv not found!"
            exit 1
          else
            echo "engines.csv created successfully"
          fi

      - name: Commit updated engines.csv and log
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add docs/data/engines.csv tools/logs/generate_engine_csv.log
          git commit -m "Auto-update engines.csv from JSON files"
          git push

      - name: Upload generated CSV as artifact
        uses: actions/upload-artifact@v4
        with:
          name: engines-csv
          path: data/engines.csv

      - name: Upload CSV log file as artifact
        uses: actions/upload-artifact@v4
        with:
          name: csv-log
          path: tools/logs/generate_engine_csv.log
