name: Validate Engine JSON Files

on:
  push:
    paths:
      - 'data/engines/**/*.json'
      - 'schemas/**'
      - 'tools/schema_validator.py'
  pull_request:
    paths:
      - 'data/engines/**/*.json'
      - 'schemas/**'
      - 'tools/schema_validator.py'

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    name: Check JSON files against schema

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run schema validator
        run: |
          python tools/schema_validator.py

      - name: Upload schema logs (on failure)
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: schema-check-log
          path: tools/logs/schema_check.log
